spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 6e1fbc65a52b1c1cae07032788e57aac
            client-secret: 9S4Hc2PVEDw47ZGw85YxEtGcbEnkPtPv
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            scope:
              - profile_nickname
              - profile_image
            authorization-grant-type: authorization_code
            client-name: Kakao
            client-authentication-method: client_secret_post
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id